insert into clientes (id, nombre, apellido, email, create_at,foto) values (1, 'Leyla', 'Feilden', 'lfeilden0@dropbox.com', '2020-08-06','');
insert into clientes (id, nombre, apellido, email, create_at,foto) values (2, 'Janka', 'Macieiczyk', 'jmacieiczyk1@blinklist.com', '2020-07-08','');
insert into clientes (id, nombre, apellido, email, create_at,foto) values (3, 'Hannah', 'Farherty', 'hfarherty2@constantcontact.com', '2019-09-21','');
insert into clientes (id, nombre, apellido, email, create_at,foto) values (4, 'Kayla', 'McAline', 'kmcaline3@seattletimes.com', '2020-01-29','');
insert into clientes (id, nombre, apellido, email, create_at,foto) values (5, 'Madel', 'Gildersleaves', 'mgildersleaves4@chronoengine.com', '2020-07-05','');
insert into clientes (id, nombre, apellido, email, create_at,foto) values (6, 'Crin', 'Hodge', 'chodge5@mapy.cz', '2020-08-15','');
insert into clientes (id, nombre, apellido, email, create_at,foto) values (7, 'Garvy', 'Husher', 'ghusher6@google.com.au', '2020-08-08','');
insert into clientes (id, nombre, apellido, email, create_at,foto) values (8, 'Diannne', 'Bollins', 'dbollins7@weebly.com', '2019-12-05','');
insert into clientes (id, nombre, apellido, email, create_at,foto) values (9, 'Gregory', 'Sieghart', 'gsieghart8@mashable.com', '2019-10-05','');
insert into clientes (id, nombre, apellido, email, create_at,foto) values (10, 'Danila', 'Leagas', 'dleagas9@quantcast.com', '2019-09-23','');
insert into clientes (id, nombre, apellido, email, create_at,foto) values (11, 'Hendrick', 'Dorbon', 'hdorbona@abc.net.au', '2020-01-14','');
insert into clientes (id, nombre, apellido, email, create_at,foto) values (12, 'Shannan', 'MacClure', 'smacclureb@ustream.tv', '2019-10-30','');
insert into clientes (id, nombre, apellido, email, create_at,foto) values (13, 'Thatch', 'Heard', 'theardc@ezinearticles.com', '2020-01-06','');
insert into clientes (id, nombre, apellido, email, create_at,foto) values (14, 'Hillie', 'Allewell', 'hallewelld@mtv.com', '2020-03-28','');
insert into clientes (id, nombre, apellido, email, create_at,foto) values (15, 'Montgomery', 'Leaver', 'mleavere@ning.com', '2020-01-18','');
insert into clientes (id, nombre, apellido, email, create_at,foto) values (16, 'Magdalen', 'Sillwood', 'msillwoodf@moonfruit.com', '2020-07-07','');
insert into clientes (id, nombre, apellido, email, create_at,foto) values (17, 'Gunther', 'Striker', 'gstrikerg@sphinn.com', '2019-12-19','');
insert into clientes (id, nombre, apellido, email, create_at,foto) values (18, 'Oswald', 'Lear', 'olearh@wiley.com', '2020-04-27','');
insert into clientes (id, nombre, apellido, email, create_at,foto) values (19, 'Blane', 'Belchem', 'bbelchemi@freewebs.com', '2020-08-11','');
insert into clientes (id, nombre, apellido, email, create_at,foto) values (20, 'Errick', 'Pietruszka', 'epietruszkaj@phpbb.com', '2020-02-03','');
insert into clientes (id, nombre, apellido, email, create_at,foto) values (21, 'Jehu', 'Stopforth', 'jstopforthk@networksolutions.com', '2019-09-06','');
insert into clientes (id, nombre, apellido, email, create_at,foto) values (22, 'Maura', 'Bauser', 'mbauserl@photobucket.com', '2019-11-15','');

insert into productos (nombre, precio ,create_at) values ('Shallots', 787.49,NOW());
insert into productos (nombre, precio ,create_at) values ('Scallops - 20/30', 928.89,NOW());
insert into productos (nombre, precio ,create_at) values ('Chocolate - Milk', 205.54,NOW()); 
insert into productos (nombre, precio ,create_at) values ('Muffin Mix - Banana Nut', 204.21,NOW());
insert into productos (nombre, precio ,create_at) values ('Pastry - Chocolate Chip Muffin', 315.72,NOW());
insert into productos (nombre, precio ,create_at) values ('Banana', 932.82,NOW());
insert into productos (nombre, precio ,create_at) values ('Pur Source', 250.13,NOW());
insert into productos (nombre, precio ,create_at) values ('Pastry - Mini French Pastries', 155.07,NOW());
insert into productos (nombre, precio ,create_at) values ('Pasta - Lasagna, Dry', 195.01,NOW());
insert into productos (nombre, precio ,create_at) values ('Shrimp - Prawn', 601.6,NOW());
insert into productos (nombre, precio ,create_at) values ('Salmon - Fillets', 914.82,NOW());
insert into productos (nombre, precio ,create_at) values ('Vol Au Vents', 505.94,NOW());
insert into productos (nombre, precio ,create_at) values ('Lid Tray - 16in Dome', 730.09,NOW());
insert into productos (nombre, precio ,create_at) values ('Liners - Baking Cups', 131.83,NOW());
insert into productos (nombre, precio ,create_at) values ('Bread - Rye', 604.84,NOW());
insert into productos (nombre, precio ,create_at) values ('Broom - Angled', 306.08,NOW());
insert into productos (nombre, precio ,create_at) values ('Pail For Lid 1537', 954.82,NOW());
insert into productos (nombre, precio ,create_at) values ('Bread - Wheat Baguette', 968.55,NOW());
insert into productos (nombre, precio ,create_at) values ('Grand Marnier', 532.24,NOW());
insert into productos (nombre, precio ,create_at) values ('Sugar - Icing', 476.01,NOW());